name: Terminus
main: com.github.archessmn.TerminusPlugin.main
version: 1.0.0
api-version: 1.16

commands:
  spawn:
    description: Teleports the player to spawn.

  prefix:
    description: Sets a player's prefix (op only).

  nick:
    description: Sets a player's nickname (op only).

  suffix:
    description: Sets a player's suffix (op only).

  vanish:
    description: Makes the sender invisible (op only).